# Generated by Django 5.1.5 on 2025-03-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtachesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'A faire'), ('in_progress', 'En cours'), ('completed', 'Terminée')], default='to_do', max_length=20),
        ),
    ]
